### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by FrankHeijden** [Rayzr522/JSONMessage#4]
Hey,

There's an issue with having bold & normal text in the same MessagePart. - the tooltip / assets don't get formatted correctly.

example code:
```
public void sendExample(Player player) {
        JSONMessage json = JSONMessage.create(ChatColor.translateAlternateColorCodes('&', "&3Colored &b&lMessage &3with some boldyness"));
        json.tooltip("this tooltip is not formatted correctly");
        json.send(player);
    }
```

in-game:
![2018-05-06_14 43 29](https://user-images.githubusercontent.com/22407829/39673414-ffb84bc6-513b-11e8-9bce-89f763ae8ee5.png)

**Comment by Rayzr522** [comment]
How is the tooltip not formatted correctly? I seem to be missing whatever the problem is.

**Comment by FrankHeijden** [comment]
It's difficult to explain, you should try the above method out and see for yourself, the hover message will still be there after the last word (but its blank)

**Comment by Andre601** [comment]
Perhaps the `ChatColor.translateAlternateColorCodes` is the issue? It's a bad way anyway which you should avoid as methods such as `color(ChatColor)` and `then(String)` exist to handle this.

Also on what version are you. Afaik are there some MC versions that are known to have some broken JSON stuff (Hover-text being longer than text and such) and this is sometimes also caused by plugins like ViaVersion.

**Comment by FrankHeijden** [comment]
Hi, I think we can close the issue, I haven’t worked for a very long time with this library, so it could be that this is no longer an issue.

**Comment by Rayzr522** [comment]
@Andre601 @FrankHeijden thanks! likely was, as @Andre601 mentioned, an MC or ViaVersion bug. will close for now :)
